### ISSUE TITLE
Error when building in iOS 7 

### ISSUE THREAD

**Issue by arilsonkarmo** [mapbox/mapbox-ios-example#19]
clang: error: -fembed-bitcode is not supported on versions of iOS prior to 6.0

someone solved this?

**Comment by friedbunny** [comment]
Hi @arilsonkarmo, couple things:

- This is an example project for the deprecated, legacy v1.x Mapbox iOS SDK, which [lives here](https://github.com/mapbox/mapbox-ios-sdk-legacy).
- Check out the awesome vector SDK that has replaced v1: https://www.mapbox.com/ios-sdk/
- If you need to use the legacy SDK and build with Xcode 7, you'll have to drop iOS 5 support.
